In [7]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
import pickle
from sklearn import metrics
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier

In [2]:
data = pd.read_csv("dataset_eq.csv")

In [4]:
data = np.array(data)
print(data)
X = data[:, 0:-1]
y = data[:,-1]
y = y.astype('int')
X = X.astype('int')

[[29.06 77.42  5.    2.5 ]
 [19.93 72.92  5.    2.4 ]
 [31.5  74.37 33.    3.4 ]
 ...
 [22.5  88.1  10.    3.6 ]
 [24.6  94.2  54.    3.5 ]
 [14.5  92.9  10.    4.6 ]]


In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=0)

print(X_train,y_train)
rfc = RandomForestClassifier()
rfc.fit(X_train, y_train)
y_pred = rfc.predict(X_test)

print(metrics.accuracy_score(y_test, y_pred))

[[ 22  94  10]
 [ 27  75   5]
 [ 34  76  10]
 ...
 [ 31  76   5]
 [ 23  70  10]
 [ 37  72 125]] [4 2 2 ... 3 4 4]
0.5588235294117647


In [9]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score

# creating a Gradient Boosting model
model = GradientBoostingClassifier()

# training the model
clf = model.fit(X_train, y_train)

# making predictions
y_pred = clf.predict(X_test)

# evaluating accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.5808823529411765


In [11]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

# creating an instance of the Support Vector Classifier
model = SVC(gamma='auto')

# training the model
clf = model.fit(X_train, y_train)

# making predictions
y_pred = clf.predict(X_test)

# evaluating accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.5680147058823529
